swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Bridge server"
  contact:
    email: "info@geocat.net"
  license:
    name: "MIT License"
    url: "https://opensource.org/licenses/MIT"
host: "localhost:8080"
basePath: "/"
tags:
- name: "publish"
- name: "data"
- name: "metadata"
- name: "servers"
schemes:
- "http"
- "https"

paths:
  /publish:
    post:
      tags:
      - "publish"
      summary: "Publishes a project"
      description: ""      
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "project"
        in: "body"
        required: true
        schema:
            $ref: "#/definitions/Project"
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/Report"       
        
definitions:
  Server:
    type: "object"
    properties:
      name:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"        
      config:        
        type: "object"
      servertye:
        type: "string"
  Project:
    type: "object"
    properties:
      name:
        type: "string"
      servers:
        type: "object"
        properties:
          data:
            type: "#/definitions/Layer"
          metadata:
            type: "#/definitions/Layer"         
      layers:
        type: "array"
        items:
          $ref: "#/definitions/Layer"
      groups:
        type: "object"
      onlysymbology:
        type: "boolean"
  Layer:
    type: "object"
    properties:
      name:
        type: "string"
      id:
        type: "string"        
      data:
        type: "object"
        properties:
          sourcetype:
            type: "string"
            enum: 
              - vectorfile
              - rasterfile
              - postgis
          source:
            type: "string"
      metadata:
        type: "string"        
      style:
        type: "object"
        properties:
          geostyler:
            type: "string"
          icons:
            type: "array"
            items:
              type: "string"
  Report:
    type: "object"
    properties:
      errors:
        type: "array"
        items:
          type: "string"
      warnings:
        type: "array"
        items:
          type: "string"






